language: python

branches:
  only:
    - master


install:
  - python --version 
  - make deps
  - make develop

script-anchors:
  - &script-linux
    - make docs
    - make lint
    - make coverage
    - codecov

matrix:
  include:
    - os: linux
      sudo: false
      dist: xenial   # required for Python >= 3.7
      python: "3.7"
      script: *script-linux
    