language: python

branches:
  only:
    - master


install:
  - python --version 
  - make deps
  - make develop

script-anchors:
  - &script-linux
    - make lint
    - make coverage
    - codecov
    - make docs

matrix:
  include:
    - os: linux
      sudo: false
      dist: xenial   # required for Python >= 3.7
      python: "3.7"
      script: *script-linux
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/_build/html
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master