"""Defines the jucer file xml tag & attribute keys
"""

# PROJECT
ATTRIBUTE_ID = 'id'
ATTRIBUTE_NAME = 'name'
ATTRIBUTE_PROJECT_TYPE = 'projectType'
ATTRIBUTE_JUCER_VERSION = 'jucerVersion'
ATTRIBUTE_VERSION = 'version'
ATTRIBUTE_COMPANY = 'companyName'
ATTRIBUTE_COMPANY_WEBSITE = 'companyWebsite'
ATTRIBUTE_COMPANY_EMAIL = 'companyEmail'
ATTRIBUTE_COMPANY_COPYRIGHT = 'companyCopyright'
ATTRIBUTE_BUNDLE_IDENTIFIER = 'bundleIdentifier'
ATTRIBUTE_PLUGIN_NAME = 'pluginName'
ATTRIBUTE_PLUGIN_DESC = 'pluginDesc'
ATTRIBUTE_PLUGIN_MANUFACTURER = 'pluginManufacturer'
ATTRIBUTE_PLUGIN_MANUFACTURER_CODE = 'pluginManufacturerCode'
ATTRIBUTE_PLUGIN_CODE = 'pluginCode'
ATTRIBUTE_PLUGIN_AU_PREFIX = 'pluginAUExportPrefix'
ATTRIBUTE_PLUGIN_VST_CATEGORY = 'pluginVST3Category'
ATTRIBUTE_AAX_IDENTIFIER = 'aaxIdentifier'
ATTRIBUTE_BINARY_DATA_NAMESPACE = 'binaryDataNamespace'
ATTRIBUTE_CPP_STANDARD = 'cppLanguageStandard'
ATTRIBUTE_PLUGIN_FORMATS = 'pluginFormats'
ATTRIBUTE_SPLASH_SCREEN = 'displaySplashScreen'
ATTRIBUTE_REPORT_APP_USAGE = 'reportAppUsage'
ATTRIBUTE_COMPILER_FLAGS = 'compilerFlagSchemes'
ATTRIBUTE_LINE_FEEDS = 'projectLineFeed'
ATTRIBUTE_DEFINES = 'defines'

# MODULES
TAG_MODULES = 'MODULES'
ATTRIBUTE_SHOW_ALL_CODE = "showAllCode"
ATTRIBUTE_USE_LOCAL_COPY = "useLocalCopy"
ATTRIBUTE_USE_GLOBAL_PATH = "useGlobalPath"


# EXPORTERS
TAG_EXPORTERS = 'EXPORTFORMATS'
TAG_CONFIGURATIONS = 'CONFIGURATIONS'
TAG_MODULEPATHS = 'MODULEPATHS'
ATTRIBUTE_BUILD_FOLDER = 'targetFolder'
